# Includes

In [1]:
import numpy as np

## Data Dimensions

    1. Scalars: 0 Dimensions
       -> (e.g 1, 2.4, 0.3)
       
    2. Vectors: 1 Dimensions, known as Length
        a. Row Vectors [ 1 2 3 ] (e.g 1x3 matrix)
        b. Column Vectors (e.g 3x1 matrix)
        
    3. Matrix: 2 Dimensions, Rows and Columns
    
    4. Tensors: n Dimensions
        -> (e.g Row of Matrices)

## Data Types and Shapes

The most common way to work with numbers in NumPy is through ndarray objects. They are similar to Python lists, but can have any number of dimensions. Also, ndarray supports fast math operations, which is just what we want.

Since it can store any number of dimensions, you can use ndarrays to represent any of the data types we covered before: scalars, vectors, matrices, or tensors.

### Scalars

Unlike python where you can use basic types like int and float. Numpy allows you to use primative types like uint8, int8, uint16, int16. When you create a NumPy array, you can specify the type - but every item in the array must have the same type.

These types are important because every object you make (vectors, matrices, tensors) eventually stores scalars.


In [8]:
s = np.array(5)

#Shape
print("shape is:", s.shape ,'..... () means 0 dimension')

#Addition
x = s + 3
print(x)



shape is: () ..... () means 0 dimension
8


### Vectors

To create a vector, you'd pass a Python list to the array function.

In [15]:
v = np.array([1,2,3])
#Shape
print("shape is:", v.shape )

#Python doesn’t understand (3) as a tuple with one item, so it requires the comma. 

#You can access an element within the vector using indices, like this:
x = v[1]

#NumPy also supports slicing. For example, to access the items from the second element onward, you would say:
print(v[1:])

shape is: (3,)
[2 3]


### Matrices 

You create matrices using NumPy's array function, just you did for vectors. However, instead of just passing in a list, you need to supply a list of lists, where each list represents a row. So to create a 3x3 matrix containing the numbers one through nine, you could do this:

In [18]:
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

#Shape
print("shape is:", m.shape )

#Checking its shape attribute would return the tuple (3, 3) to indicate it has two dimensions, each length 3.

#You can access elements of matrices just like vectors, but using additional index values. So to find the number 6 in the above matrix, you'd access m[1][2].
print(m[1][2])

shape is: (3, 3)
6


### Tensors

Tensors are just like vectors and matrices, but they can have more dimensions. For example, to create a 3x3x2x1 tensor, you could do the following:

In [20]:
t = np.array([[ [[1],[2]],[[3],[4]],[[5],[6]]],[[[7],[8]],\
    [[9],[10]],[[11],[12]]],[[[13],[14]],[[15],[16]],[[17],[17]]]])

#Shape, very hard to guess
print("shape is:", t.shape )

#Access
print(t[2][1][1][0])

shape is: (3, 3, 2, 1)
16


## Changing Shapes

Sometimes you'll need to change the shape of your data without actually changing its contents. For example, you may have a vector, which is one-dimensional, but need a matrix, which is two-dimensional. There are two ways you can do that.

In [27]:
# Given
v = np.array([1,2,3,4])

print("original: ", v.shape)

# What if we want a 4 row by 1 Column matrix
v2 = v.reshape(4,1)
print(v2)

print("after: ", v2.shape)

#One more thing about reshaping NumPy arrays: 
#if you see code from experienced NumPy users, 
#you will often see them use a special slicing syntax instead of calling reshape. 
#Using this syntax, the previous two examples would look like this:

x = v[None, :]
x2  = v[:, None]
print(x)
print(x2)

original:  (4,)
[[1]
 [2]
 [3]
 [4]]
after:  (4, 1)
[[1 2 3 4]]
[[1]
 [2]
 [3]
 [4]]


# Matrix Math

Element-wise operations -> Treeat items in matrix individually and perform same operation on each one

In [36]:
%%timeit
# Iterative Method


values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5
    
# now values holds [6,7,8,9,10]

#That makes sense, but it's a lot of code to write and it runs slowly because it's pure Python.

452 ns ± 5.78 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [39]:
%%timeit
# Matrix Math using Numpy

np_values = np.array([1,2,3,4,5])
np_values += 5


2.27 µs ± 28.5 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [42]:
# What about multiplication
np_values = np.array([1,2,3,4,5])
test = np.multiply(np_values, 5)
print(test)
#or
test2 = np_values * 5
print(test2)


[ 5 10 15 20 25]
[ 5 10 15 20 25]


In [44]:
a = np.array([[1,3],[5,7]])
# displays the following result:
# array([[1, 3],
#        [5, 7]])

b = np.array([[2,4],[6,8]])
# displays the following result:
# array([[2, 4],
#        [6, 8]])

a + b
# displays the following result
#      array([[ 3,  7],
#             [11, 15]])

#Shape must be the same to add

array([[ 3,  7],
       [11, 15]])

# Matrix Product vs Matrix Multiplication

In [48]:
# Matrix Multiplication is not Dot Product
'''
| 1 2 3 |   | 2 2 2 |   | 2 4 6 |
| 1 2 3 | x | 2 2 2 | = | 2 4 6 |
| 1 2 3 |   | 2 2 2 |   | 2 4 6 |
'''

# 1. Rule of Thumb: (AxB)•(CxD) , where B and C must be equal size becomes (AxD)
# 2.A•B != A•B

'\n| 1 2 3 |   | 2 2 2 |   | 2 4 6 |\n| 1 2 3 | x | 2 2 2 | = | 2 4 6 |\n| 1 2 3 |   | 2 2 2 |   | 2 4 6 |\n'

In [51]:
# Element-wise Multiplication

m = np.array([[1,2,3],[4,5,6]])
# displays the following result:
# array([[1, 2, 3],
#        [4, 5, 6]])

n = m * 0.25
print(n)
# displays the following result:
# array([[ 0.25,  0.5 ,  0.75],
#        [ 1.  ,  1.25,  1.5 ]])

print(m * n)
# displays the following result:
# array([[ 0.25,  1.  ,  2.25],
#        [ 4.  ,  6.25,  9.  ]])

np.multiply(m, n)   # equivalent to m * n
# displays the following result:
# array([[ 0.25,  1.  ,  2.25],
#        [ 4.  ,  6.25,  9.  ]])

[[0.25 0.5  0.75]
 [1.   1.25 1.5 ]]
[[0.25 1.   2.25]
 [4.   6.25 9.  ]]


array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [57]:
# Matrix Product

a = np.array([[1,2,3,4],[5,6,7,8]])

# displays the following result:
# array([[1, 2, 3, 4],
#        [5, 6, 7, 8]])
print(a.shape)
print(a)
# displays the following result:
# (2, 4)

b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

# displays the following result:
# array([[ 1,  2,  3],
#        [ 4,  5,  6],
#        [ 7,  8,  9],
#        [10, 11, 12]])
print(b.shape)
print(b)
# displays the following result:
# (4, 3)

c = np.matmul(a, b)
print(c)

# displays the following result:
# array([[ 70,  80,  90],
#        [158, 184, 210]])
print(c.shape)
# displays the following result:
# (2, 3)

(2, 4)
[[1 2 3 4]
 [5 6 7 8]]
(4, 3)
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 70  80  90]
 [158 184 210]]
(2, 3)


### NumPy's dot function
You may sometimes see NumPy's dot function in places where you would expect a matmul. It turns out that the results of dot and matmul are the same if the matrices are two dimensional.

In [60]:
a = np.array([[1,2],[3,4]])
a
# displays the following result:
# array([[1, 2],
#        [3, 4]])

np.dot(a,a)
# displays the following result:
# array([[ 7, 10],
#        [15, 22]])

a.dot(a)  # you can call `dot` directly on the `ndarray`
# displays the following result:
# array([[ 7, 10],
#        [15, 22]])
print(a.dot(a))

np.matmul(a,a)
# array([[ 7, 10],
#        [15, 22]])

[[ 7 10]
 [15 22]]


array([[ 7, 10],
       [15, 22]])

# Transpose

1. Swap the dimensions of the matrix : 3x2 becomes 2x3

2. Swap data, row becomes columns & vice versa

Useful? What If:
Row: We store student entry
Column: We store height, weight, color for each student

So: What if we want all the data for a feature in the dataset and not just all features for one person. Transpose!

Note: You can only safetly use a transpose in a matrix multiplication if the data is in both of your original matricies are arranged as rows

In [61]:
'''
| 1 2 3 4 |          | 1 5 |
| 5 6 7 8 | becomes  | 2 6 |
                     | 3 7 |
                     | 4 5 |
'''

'\n| 1 2 3 4 |          | 1 5 |\n| 5 6 7 8 | becomes  | 2 6 |\n                     | 3 7 |\n                     | 4 5 |\n'

In [69]:
# Transpose

m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(m)
print(m.shape)

print(m.transpose()) # or m.T
print(m.T.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
(4, 3)


### A real use case

I don't want to get into too many details about neural networks because you haven't covered them yet, but there is one place you will almost certainly end up using a transpose, or at least thinking about it.

Let's say you have the following two matrices, called inputs and weights,

In [87]:
inputs = np.array([[-0.27,  0.45,  0.64, 0.31]])
print("Inputs: " ,inputs)
print(inputs.shape)

weights = np.array([[0.02, 0.001, -0.03, 0.036], \
    [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])
print("Weights: \n" ,weights)
print(weights.shape)

print("\nWe cant dot product due to shape, enless transpose\n")

product = np.matmul(inputs, weights.T)
print(product , "\n Shape should be (1, 3)")
print(product.shape)

print("\nAlternative:\n")

product2 = np.matmul(weights, inputs.T)
print(product2 , "\n Shape should be (3, 1)")
print(product2.shape)


Inputs:  [[-0.27  0.45  0.64  0.31]]
(1, 4)
Weights: 
 [[ 0.02   0.001 -0.03   0.036]
 [ 0.04  -0.003  0.025  0.009]
 [ 0.012 -0.045  0.28  -0.067]]
(3, 4)

We cant dot product due to shape, enless transpose

[[-0.01299  0.00664  0.13494]] 
 Shape should be (1, 3)
(1, 3)

Alternative:

[[-0.01299]
 [ 0.00664]
 [ 0.13494]] 
 Shape should be (3, 1)
(3, 1)
